# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
name: 'backup-environment'
description: 'Power Platform Backup Environment Action'
inputs:
  environment-url:
    description: 'URL of Power Platform environment to backup; e.g. "https://test-env.crm.dynamics.com"'
    required: true

  backup-label:
    description: 'Label to add to the Power Platform environment backup.'
    required: true

  user-name:
    description: 'Power Platform user name, e.g. myname@my-org.onmicrosoft.com'
    required: true

  password-secret:
    description: 'Power Platform password. Do NOT checkin password, instead create a secret and reference it here with: see: https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#using-encrypted-secrets-in-a-workflow'
    required: true

runs:
  using: 'node12'
  main: '../dist/actions/backup-environment/index.js'
